//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PimApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ измерений.
        /// </summary>
        internal static string Analis {
            get {
                return ResourceManager.GetString("Analis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!!!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднее значение: .
        /// </summary>
        internal static string Avg {
            get {
                return ResourceManager.GetString("Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Среднеквадратичное отклонение: .
        /// </summary>
        internal static string Avg2 {
            get {
                return ResourceManager.GetString("Avg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверная погрешность.
        /// </summary>
        internal static string Bag {
            get {
                return ResourceManager.GetString("Bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите удалить запись?.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество измерений: .
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата cохранения измерений.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление.
        /// </summary>
        internal static string DisplayAlertHeader {
            get {
                return ResourceManager.GetString("DisplayAlertHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать результат .
        /// </summary>
        internal static string Edit1 {
            get {
                return ResourceManager.GetString("Edit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -го измерения.
        /// </summary>
        internal static string Edit2 {
            get {
                return ResourceManager.GetString("Edit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показания счетчика.
        /// </summary>
        internal static string Energy_ValuesText {
            get {
                return ResourceManager.GetString("Energy_ValuesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить ввод.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите результат .
        /// </summary>
        internal static string Enter1 {
            get {
                return ResourceManager.GetString("Enter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -го измерения.
        /// </summary>
        internal static string Enter2 {
            get {
                return ResourceManager.GetString("Enter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить ввод.
        /// </summary>
        internal static string EnterButton {
            get {
                return ResourceManager.GetString("EnterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введенные погрешности.
        /// </summary>
        internal static string EnteredValue {
            get {
                return ResourceManager.GetString("EnteredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УСЛОВИЕ (МЕНЕЕ 0,5%) НЕ ВЫПОЛНЯЕТСЯ.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введено менее 7 значений.
        /// </summary>
        internal static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип счетчика.
        /// </summary>
        internal static string Model_CounterText {
            get {
                return ResourceManager.GetString("Model_CounterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование потребителя.
        /// </summary>
        internal static string Name_OrgText {
            get {
                return ResourceManager.GetString("Name_OrgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не введено.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расчет не возможен: введено менее 3 значений.
        /// </summary>
        internal static string NonPayment {
            get {
                return ResourceManager.GetString("NonPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введены данные.
        /// </summary>
        internal static string NonValue {
            get {
                return ResourceManager.GetString("NonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        internal static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зав.№ счетчика.
        /// </summary>
        internal static string Number_CounterText {
            get {
                return ResourceManager.GetString("Number_CounterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить ввод результатов измеренной погрешности.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить действие.
        /// </summary>
        internal static string Proverka {
            get {
                return ResourceManager.GetString("Proverka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс ввода результатов измеренной погрешности.
        /// </summary>
        internal static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты измерений.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измерения сохранены.
        /// </summary>
        internal static string SaveOk {
            get {
                return ResourceManager.GetString("SaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение измерений.
        /// </summary>
        internal static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение измерений.
        /// </summary>
        internal static string SaveValue {
            get {
                return ResourceManager.GetString("SaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализ измерений.
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр инструкции.
        /// </summary>
        internal static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История измерений.
        /// </summary>
        internal static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УСЛОВИЕ ВЫПОЛНЯЕТСЯ.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр измерений.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введено  .
        /// </summary>
        internal static string Vvod1 {
            get {
                return ResourceManager.GetString("Vvod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  значений (-я): .
        /// </summary>
        internal static string Vvod2 {
            get {
                return ResourceManager.GetString("Vvod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
